name: ns0-deploy

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

defaults:
    run:
        working-directory: express

jobs:
    build:
        runs-on: [self-hosted, ns0]

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Create env file
              run: |
                  touch .env
                  echo MONGODB_="${{ secrets.MONGODB_ }}" >> .env
                  echo SERVER_="s0" >> .env
                  echo NODE_="n0" >> .env
                  echo PORT_="6969" >> .env
                  cat .env
            - name: Wait for 30 seconds
              uses: jakejarvis/wait-action@master
              with:
                  time: "60s"
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: pm2 restart ns0
            # Created by: https://www.levminer.com
