name: ns0-deploy

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

defaults:
  run:
    working-directory: express

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
     - uses: SpicyPizza/create-envfile@v1
      with:
        envkey_MONGODB_: ${{ secrets.MONGODB_ }}
        envkey_SERVER_: "s0"
        envkey_NODE_: "n0"
        envkey_PORT_: "6969"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: pm2 restart ns0
