name: ns1-deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

defaults:
    run:
        working-directory: express

jobs:
    build:
        runs-on: [self-hosted, ns1]

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Create env file
              run: |
                  touch .env
                  echo MONGODB_="${{ secrets.MONGODB_ }}" >> .env
                  echo SERVER_="s0" >> .env
                  echo NODE_="n1" >> .env
                  echo PORT_="8080" >> .env
                  cat .env
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: pm2 restart ns1
            # Created by: https://www.levminer.com
